=== Lefted/Deklarative-Programmierung-Uebung/src/de/hka/xml/uebungen/Uebung3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="uebung3" elementFormDefault="qualified"
	xmlns="uebung3">

	<!-- definition von komplexen elementen -->
	<xs:element name="telefon">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="vorwahl" type="xs:normalizedString" />
				<xs:element name="nummer" type="xs:normalizedString" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="fax">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="vorwahl" type="xs:normalizedString" />
				<xs:element name="nummer" type="xs:normalizedString" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="unternehmer">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="anschrift">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="firmen-name"
								type="xs:normalizedString" minOccurs="0"/>
							<xs:element name="vorname" type="xs:normalizedString" minOccurs="0"></xs:element>
							<xs:element name="nachname" type="xs:normalizedString" minOccurs="0"></xs:element>
							<xs:element name="postleitzahl"
								type="xs:positiveInteger" />
							<xs:element name="stadt" type="xs:normalizedString" />
							<xs:element name="strasse" type="xs:normalizedString" />
							<xs:element name="haus-nummer" type="xs:normalizedString" />
							<xs:element ref="telefon" minOccurs="0"/>
							<xs:element ref="fax" minOccurs="0"/>
							<xs:element name="e-mail" type="xs:normalizedString" minOccurs="0"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="steuernummer" type="xs:normalizedString" minOccurs="0"/>
				<xs:element name="umsatzsteuer-identifikationsnummer" type="xs:normalizedString" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="leistungs-empfaenger">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="anrede" type="xs:normalizedString" />
				<xs:element name="vorname" type="xs:normalizedString" minOccurs="0"/>
				<xs:element name="nachname" type="xs:normalizedString" />
				<xs:element name="postleitzahl" type="xs:positiveInteger" />
				<xs:element name="stadt" type="xs:normalizedString" />
				<xs:element name="strasse" type="xs:normalizedString" />
				<xs:element name="haus-nummer" type="xs:normalizedString" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="rechnungsbetrag-type">
		<xs:sequence>
			<xs:element name="betrag" type="xs:double" />
			<xs:element name="waehrung" type="xs:normalizedString" />
		</xs:sequence>
	</xs:complexType>

	<xs:element name="entgelt">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="bruttobetrag" type="rechnungsbetrag-type" />
				<xs:element name="nettobetrag" type="rechnungsbetrag-type" minOccurs="0"/>
				<xs:element name="mehrwertsteuer-gesamt" type="rechnungsbetrag-type" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="abrechnungs-position">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="menge" type="xs:positiveInteger" />
				<xs:element name="einheit" type="xs:normalizedString" />
				<xs:element name="leistung" type="xs:string" />
				<xs:element name="einzel-preis" type="rechnungsbetrag-type" minOccurs="0"/>
				<xs:element name="gesamt-preis" type="rechnungsbetrag-type" />
				<xs:element name="mehrwertsteuer-prozent" type="xs:positiveInteger" minOccurs="0"/>
				<xs:element name="datum" type="xs:date" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="positionsnummer" type="xs:positiveInteger" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="abrechnungs-positionen">
		<xs:complexType>
			<xs:choice>
				<xs:element ref="abrechnungs-position" maxOccurs="unbounded"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>

	<!-- leere element -->
	<xs:complexType name="barzahlung-type">
		<xs:attribute name="barzahlungid" type="xs:positiveInteger"></xs:attribute>
	</xs:complexType>

	<xs:element name="zahlungsart">
		<xs:complexType>
			<xs:all>
				<xs:element name="bank" type="xs:normalizedString" minOccurs="0"/>
				<xs:element name="name" type="xs:normalizedString" minOccurs="0"/>
				<xs:element name="iban" type="xs:normalizedString" minOccurs="0"/>
				<xs:element name="bic" type="xs:normalizedString" minOccurs="0"/>
				<xs:element name="blz" type="xs:normalizedString" minOccurs="0"/>
				<xs:element name="kontonummer" type="xs:normalizedString" minOccurs="0"/>
				<xs:element name="bitcoin-adresse" type="xs:normalizedString" minOccurs="0"/>
				<xs:element name="barzahlung" type="barzahlung-type" minOccurs="0"/>
			</xs:all>
		</xs:complexType>
	</xs:element>

	<xs:element name="zahlungsarten">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="zahlungsart" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:simpleType name="rechnungsnummer-type">
		<xs:restriction base="xs:normalizedString">
			<xs:pattern value="(\d+[-/ ]?)+" />
		</xs:restriction>
	</xs:simpleType>

	<xs:element name="rechnungen">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="rechnung" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="unternehmer"/>
							<xs:element ref="leistungs-empfaenger"/>
							<xs:element name="ausstellungsdatum" type="xs:date"/>
							<xs:element name="rechnungsnummer" type="rechnungsnummer-type"/>
							<xs:element ref="entgelt"/>
							<xs:element ref="abrechnungs-positionen"/>
							<xs:element ref="zahlungsarten"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="name" type="xs:normalizedString" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Lefted/Deklarative-Programmierung-Uebung/src/de/hka/xml/uebungen/Uebung3.xml
<?xml version="1.0" encoding="UTF-8"?>
<rechnungen
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="uebung3 Uebung3.xsd"
	xmlns="uebung3"
	name="XML">
	<rechnung>
		<unternehmer>
			<anschrift>
				<firmen-name>Kleintier Meier GmbH</firmen-name>
				<postleitzahl>81828</postleitzahl>
				<stadt>Machthausen</stadt>
				<strasse>Meierring</strasse>
				<haus-nummer>3</haus-nummer>
				<telefon>
					<vorwahl>0777</vorwahl>
					<nummer>987987</nummer>
				</telefon>
				<fax>
					<vorwahl>0777</vorwahl>
					<nummer>987789</nummer>
				</fax>
				<e-mail>klein.meier@tiere.de</e-mail>
			</anschrift>
			<steuernummer>88 123/8282 2</steuernummer>
		</unternehmer>
		<leistungs-empfaenger>
			<anrede>Frau</anrede>
			<vorname>Sybille</vorname>
			<nachname>Sonder-Suttelrau</nachname>
			<postleitzahl>77070</postleitzahl>
			<stadt>Siedelsuderstadt</stadt>
			<strasse>Am Suettelbach</strasse>
			<haus-nummer>17</haus-nummer>
		</leistungs-empfaenger>
		<ausstellungsdatum>2017-01-15</ausstellungsdatum>
		<rechnungsnummer>657321</rechnungsnummer>
		<entgelt>
			<bruttobetrag>
				<betrag>962.22</betrag>
				<waehrung>EUR</waehrung>
			</bruttobetrag>
			<nettobetrag>
				<betrag>808.59</betrag>
				<waehrung>EUR</waehrung>
			</nettobetrag>
			<mehrwertsteuer-gesamt>
				<betrag>153.63</betrag>
				<waehrung>EUR</waehrung>
			</mehrwertsteuer-gesamt>
		</entgelt>
		<abrechnungs-positionen>
			<abrechnungs-position positionsnummer="1">
				<menge>100</menge>
				<einheit>Stueck</einheit>
				<leistung>Antike Holzwuermer</leistung>
				<einzel-preis>
					<betrag>1.50</betrag>
					<waehrung>EUR</waehrung>
				</einzel-preis>
				<gesamt-preis>
					<betrag>150.00</betrag>
					<waehrung>EUR</waehrung>
				</gesamt-preis>
				<mehrwertsteuer-prozent>19</mehrwertsteuer-prozent>
				<datum>2017-01-01</datum>
			</abrechnungs-position>
			<abrechnungs-position positionsnummer="2">
				<menge>1</menge>
				<einheit>Stueck</einheit>
				<leistung>Holzwurmfutter</leistung>
				<einzel-preis>
					<betrag>34.45</betrag>
					<waehrung>EUR</waehrung>
				</einzel-preis>
				<gesamt-preis>
					<betrag>34.45</betrag>
					<waehrung>EUR</waehrung>
				</gesamt-preis>
				<mehrwertsteuer-prozent>19</mehrwertsteuer-prozent>
				<datum>2017-01-12</datum>
			</abrechnungs-position>
			<abrechnungs-position positionsnummer="3">
				<menge>1</menge>
				<einheit>Stueck</einheit>
				<leistung>Steinlaus, Petrophaga lorioti</leistung>
				<einzel-preis>
					<betrag>777.77</betrag>
					<waehrung>EUR</waehrung>
				</einzel-preis>
				<gesamt-preis>
					<betrag>777.77</betrag>
					<waehrung>EUR</waehrung>
				</gesamt-preis>
				<mehrwertsteuer-prozent>19</mehrwertsteuer-prozent>
				<datum>2017-01-12</datum>
			</abrechnungs-position>
		</abrechnungs-positionen>
		<zahlungsarten>
			<zahlungsart>
				<bank>Sparkasse Karlsruhe</bank>
				<name>Kleintier Meier</name>
				<blz>66050101</blz>
				<kontonummer>987654321</kontonummer>
			</zahlungsart>
		</zahlungsarten>
	</rechnung>
	<rechnung>
		<unternehmer>
			<anschrift>
				<firmen-name>Rochade-La Hoff AG</firmen-name>
				<postleitzahl>79639</postleitzahl>
				<stadt>Grenzych-Wahlen</stadt>
				<strasse>An der Chemie</strasse>
				<haus-nummer>17</haus-nummer>
				<telefon>
					<vorwahl>07624</vorwahl>
					<nummer>666 333 999</nummer>
				</telefon>
				<fax>
					<vorwahl>07624</vorwahl>
					<nummer>666 333 990</nummer>
				</fax>
			</anschrift>
			<umsatzsteuer-identifikationsnummer>DE333666999</umsatzsteuer-identifikationsnummer>
		</unternehmer>
		<leistungs-empfaenger>
			<anrede>Dr. med.</anrede>
			<vorname>Cyprian</vorname>
			<nachname>Zottel</nachname>
			<postleitzahl>13023</postleitzahl>
			<stadt>Zotenheim</stadt>
			<strasse>Soddelstrudel</strasse>
			<haus-nummer>5a</haus-nummer>
		</leistungs-empfaenger>
		<ausstellungsdatum>2017-08-08</ausstellungsdatum>
		<rechnungsnummer>98-798-7987</rechnungsnummer>
		<entgelt>
			<bruttobetrag>
				<betrag>621.94</betrag>
				<waehrung>EUR</waehrung>
			</bruttobetrag>
			<nettobetrag>
				<betrag>490.22</betrag>
				<waehrung>EUR</waehrung>
			</nettobetrag>
			<mehrwertsteuer-gesamt>
				<betrag>116.74</betrag>
				<waehrung>EUR</waehrung>
			</mehrwertsteuer-gesamt>
		</entgelt>
		<abrechnungs-positionen>
			<abrechnungs-position positionsnummer="1">
				<menge>3</menge>
				<einheit>Packungen</einheit>
				<leistung>Grippemittel Tumifla</leistung>
				<einzel-preis>
					<betrag>120.00</betrag>
					<waehrung>EUR</waehrung>
				</einzel-preis>
				<gesamt-preis>
					<betrag>360.00</betrag>
					<waehrung>EUR</waehrung>
				</gesamt-preis>
				<mehrwertsteuer-prozent>19</mehrwertsteuer-prozent>
			</abrechnungs-position>
			<abrechnungs-position positionsnummer="2">
				<menge>2</menge>
				<einheit>Liter</einheit>
				<leistung>Abf√ºhrmittel Wech damit</leistung>
				<einzel-preis>
					<betrag>99.99</betrag>
					<waehrung>EUR</waehrung>
				</einzel-preis>
				<gesamt-preis>
					<betrag>199.98</betrag>
					<waehrung>EUR</waehrung>
				</gesamt-preis>
				<mehrwertsteuer-prozent>19</mehrwertsteuer-prozent>
			</abrechnungs-position>
			<abrechnungs-position positionsnummer="3">
				<menge>2</menge>
				<einheit>Stueck</einheit>
				<leistung>Energieriegel Satto</leistung>
				<einzel-preis>
					<betrag>5.98</betrag>
					<waehrung>EUR</waehrung>
				</einzel-preis>
				<gesamt-preis>
					<betrag>11.96</betrag>
					<waehrung>EUR</waehrung>
				</gesamt-preis>
				<mehrwertsteuer-prozent>7</mehrwertsteuer-prozent>
			</abrechnungs-position>
		</abrechnungs-positionen>
		<zahlungsarten>
			<zahlungsart>
				<bank>DEutsche Bank Loerrach</bank>
				<iban>DE18 6837 003 0999 6663 33</iban>
				<bic>UBSWCHZH80H</bic>
			</zahlungsart>
		</zahlungsarten>
	</rechnung>
	<rechnung>
		<unternehmer>
			<anschrift>
				<firmen-name>Bestattungen Unterberg</firmen-name>
				<postleitzahl>43210</postleitzahl>
				<stadt>Ultursingen</stadt>
				<strasse>Oberbergweg</strasse>
				<haus-nummer>5</haus-nummer>
				<telefon>
					<vorwahl>0478</vorwahl>
					<nummer>777 555</nummer>
				</telefon>
				<e-mail>unter@berg.de</e-mail>
			</anschrift>
			<umsatzsteuer-identifikationsnummer>DE 987654321</umsatzsteuer-identifikationsnummer>
		</unternehmer>
		<leistungs-empfaenger>
			<anrede>Familie</anrede>
			<nachname>Urmel</nachname>
			<postleitzahl>43210</postleitzahl>
			<stadt>Ultursingen</stadt>
			<strasse>Ulturenstrasse</strasse>
			<haus-nummer>764</haus-nummer>
		</leistungs-empfaenger>
		<ausstellungsdatum>2017-10-19</ausstellungsdatum>
		<rechnungsnummer>893 213 11</rechnungsnummer>
		<entgelt>
			<bruttobetrag>
				<betrag>878.49</betrag>
				<waehrung>EUR</waehrung>
			</bruttobetrag>
			<nettobetrag>
				<betrag>738.23</betrag>
				<waehrung>EUR</waehrung>
			</nettobetrag>
			<mehrwertsteuer-gesamt>
				<betrag>140.26</betrag>
				<waehrung>EUR</waehrung>
			</mehrwertsteuer-gesamt>
		</entgelt>
		<abrechnungs-positionen>
			<abrechnungs-position positionsnummer="1">
				<menge>1</menge>
				<einheit>Stueck</einheit>
				<leistung>Urne, Eiche massiv</leistung>
				<einzel-preis>
					<betrag>299.99</betrag>
					<waehrung>EUR</waehrung>
				</einzel-preis>
				<gesamt-preis>
					<betrag>299.99</betrag>
					<waehrung>EUR</waehrung>
				</gesamt-preis>
			</abrechnungs-position>
			<abrechnungs-position positionsnummer="2">
				<menge>1</menge>
				<einheit>Stueck</einheit>
				<leistung>Ueberfuehrung Krematorium Feuerbach inkl. Begleitpersonal</leistung>
				<einzel-preis>
					<betrag>349.00</betrag>
					<waehrung>EUR</waehrung>
				</einzel-preis>
				<gesamt-preis>
					<betrag>349.00</betrag>
					<waehrung>EUR</waehrung>
				</gesamt-preis>
			</abrechnungs-position>
			<abrechnungs-position positionsnummer="3">
				<menge>1</menge>
				<einheit>Stueck</einheit>
				<leistung>Dekoration</leistung>
				<einzel-preis>
					<betrag>149.50</betrag>
					<waehrung>EUR</waehrung>
				</einzel-preis>
				<gesamt-preis>
					<betrag>149.50</betrag>
					<waehrung>EUR</waehrung>
				</gesamt-preis>
			</abrechnungs-position>
			<abrechnungs-position positionsnummer="4">
				<menge>40</menge>
				<einheit>Stueck</einheit>
				<leistung>Trauerkarten inkl. Briefmarken</leistung>
				<einzel-preis>
					<betrag>2.00</betrag>
					<waehrung>EUR</waehrung>
				</einzel-preis>
				<gesamt-preis>
					<betrag>80.00</betrag>
					<waehrung>EUR</waehrung>
				</gesamt-preis>
			</abrechnungs-position>
		</abrechnungs-positionen>
		<zahlungsarten>
			<zahlungsart>
				<iban>DE16660501010077889911</iban>
			</zahlungsart>
			<zahlungsart>
				<bank>UBS Zuerich</bank>
				<bic>UBSWCHZH80H</bic>
				<kontonummer>75847683</kontonummer>
			</zahlungsart>
			<zahlungsart>
				<bitcoin-adresse>1P82rBiJHDFSav2QrKx1bvdDRVh5QnGkkZ</bitcoin-adresse>
			</zahlungsart>
		</zahlungsarten>
	</rechnung>
</rechnungen>
