=== Lefted/Deklarative-Programmierung-Uebung/src/de/hka/xml/uebungen/Uebung2.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT rechnungen (rechnung)*>
<!ELEMENT rechnung (unternehmer, leistungs-empfaenger, ausstellungsdatum, rechnungsnummer, entgelt, abrechnungs-positionen)>
<!ELEMENT unternehmer (anschrift, (steuernummer | umsatzsteuer-identifikationsnummer))>
<!ELEMENT anschrift (firmen-name, postleitzahl, stadt, strasse, haus-nummer, telefon, fax, e-mail?)>
<!ELEMENT firmen-name (#PCDATA)>
<!ELEMENT postleitzahl (#PCDATA)>
<!ELEMENT stadt (#PCDATA)>
<!ELEMENT strasse (#PCDATA)>
<!ELEMENT haus-nummer (#PCDATA)>
<!ELEMENT telefon (vorwahl, nummer)>
<!ELEMENT vorwahl (#PCDATA)>
<!ELEMENT nummer (#PCDATA)>
<!ELEMENT fax (vorwahl, nummer)>
<!ELEMENT e-mail (#PCDATA)>
<!ELEMENT steuernummer (#PCDATA)>
<!ELEMENT umsatzsteuer-identifikationsnummer (#PCDATA)>
<!ELEMENT leistungs-empfaenger (anrede, vorname, nachname, postleitzahl, stadt, strasse, haus-nummer)>
<!ELEMENT anrede (#PCDATA)>
<!ELEMENT vorname (#PCDATA)>
<!ELEMENT nachname (#PCDATA)>
<!ELEMENT ausstellungsdatum (#PCDATA)>
<!ELEMENT rechnungsnummer (#PCDATA)>
<!ELEMENT entgelt (rechnungsbetrag, nettobetrag, mehrwertsteuer-gesamt)>
<!ELEMENT rechnungsbetrag (betrag, waehrung)>
<!ELEMENT betrag (#PCDATA)>
<!ELEMENT waehrung (#PCDATA)>
<!ELEMENT nettobetrag (betrag, waehrung)>
<!ELEMENT mehrwertsteuer-gesamt (betrag, waehrung)>
<!ELEMENT abrechnungs-positionen (abrechnungs-position)*>
<!ELEMENT abrechnungs-position (menge, einheit, leistung, einzel-preis, gesamt-preis, mehrwertsteuer-prozent, datum?)>
<!ATTLIST abrechnungs-position positionsnummer CDATA #REQUIRED>
<!ELEMENT menge (#PCDATA)>
<!ELEMENT einheit (#PCDATA)>
<!ELEMENT leistung (#PCDATA)>
<!ELEMENT einzel-preis (betrag, waehrung)>
<!ELEMENT gesamt-preis (betrag, waehrung)>
<!ELEMENT mehrwertsteuer-prozent (#PCDATA)>
<!ELEMENT datum (#PCDATA)>

=== Lefted/Deklarative-Programmierung-Uebung/src/de/hka/xml/uebungen/Uebung2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE rechnungen SYSTEM "Uebung2.dtd">
<rechnungen>
	<rechnung>
		<unternehmer>
			<anschrift>
				<firmen-name>Kleintier Meier GmbH</firmen-name>
				<postleitzahl>81828</postleitzahl>
				<stadt>Machthausen</stadt>
				<strasse>Meierring</strasse>
				<haus-nummer>3</haus-nummer>
				<telefon>
					<vorwahl>0777</vorwahl>
					<nummer>987987</nummer>
				</telefon>
				<fax>
					<vorwahl>0777</vorwahl>
					<nummer>987789</nummer>
				</fax>
				<e-mail>klein.meier@tiere.de</e-mail>
			</anschrift>
			<steuernummer>88 123/8282 2</steuernummer>
		</unternehmer>
		<leistungs-empfaenger>
			<anrede>Frau</anrede>
			<vorname>Sybille</vorname>
			<nachname>Sonder-Suttelrau</nachname>
			<postleitzahl>77070</postleitzahl>
			<stadt>Siedelsuderstadt</stadt>
			<strasse>Am Suettelbach</strasse>
			<haus-nummer>17</haus-nummer>
		</leistungs-empfaenger>
		<ausstellungsdatum>2017-01-15</ausstellungsdatum>
		<rechnungsnummer>657321</rechnungsnummer>
		<entgelt>
			<rechnungsbetrag>
				<betrag>962.22</betrag>
				<waehrung>EUR</waehrung>
			</rechnungsbetrag>
			<nettobetrag>
				<betrag>808.59</betrag>
				<waehrung>EUR</waehrung>
			</nettobetrag>
			<mehrwertsteuer-gesamt>
				<betrag>153.63</betrag>
				<waehrung>EUR</waehrung>
			</mehrwertsteuer-gesamt>
		</entgelt>
		<abrechnungs-positionen>
			<abrechnungs-position positionsnummer="1">
				<menge>100</menge>
				<einheit>Stueck</einheit>
				<leistung>Antike Holzwuermer</leistung>
				<einzel-preis>
					<betrag>1.50</betrag>
					<waehrung>EUR</waehrung>
				</einzel-preis>
				<gesamt-preis>
					<betrag>150.00</betrag>
					<waehrung>EUR</waehrung>
				</gesamt-preis>
				<mehrwertsteuer-prozent>19</mehrwertsteuer-prozent>
				<datum>2017-01-01</datum>
			</abrechnungs-position>
			<abrechnungs-position positionsnummer="2">
				<menge>1</menge>
				<einheit>Stueck</einheit>
				<leistung>Holzwurmfutter</leistung>
				<einzel-preis>
					<betrag>34.45</betrag>
					<waehrung>EUR</waehrung>
				</einzel-preis>
				<gesamt-preis>
					<betrag>34.45</betrag>
					<waehrung>EUR</waehrung>
				</gesamt-preis>
				<mehrwertsteuer-prozent>19</mehrwertsteuer-prozent>
				<datum>2017-01-12</datum>
			</abrechnungs-position>
			<abrechnungs-position positionsnummer="3">
				<menge>1</menge>
				<einheit>Stueck</einheit>
				<leistung>Steinlaus, Petrophaga lorioti</leistung>
				<einzel-preis>
					<betrag>777.77</betrag>
					<waehrung>EUR</waehrung>
				</einzel-preis>
				<gesamt-preis>
					<betrag>777.77</betrag>
					<waehrung>EUR</waehrung>
				</gesamt-preis>
				<mehrwertsteuer-prozent>19</mehrwertsteuer-prozent>
				<datum>2017-01-12</datum>
			</abrechnungs-position>
		</abrechnungs-positionen>
	</rechnung>
	<rechnung>
		<unternehmer>
			<anschrift>
				<firmen-name>Rochade-La Hoff AG</firmen-name>
				<postleitzahl>79639</postleitzahl>
				<stadt>Grenzych-Wahlen</stadt>
				<strasse>An der Chemie</strasse>
				<haus-nummer>17</haus-nummer>
				<telefon>
					<vorwahl>07624</vorwahl>
					<nummer>666 333 999</nummer>
				</telefon>
				<fax>
					<vorwahl>07624</vorwahl>
					<nummer>666 333 990</nummer>
				</fax>
			</anschrift>
			<umsatzsteuer-identifikationsnummer>DE333666999</umsatzsteuer-identifikationsnummer>
		</unternehmer>
		<leistungs-empfaenger>
			<anrede>Dr. med.</anrede>
			<vorname>Cyprian</vorname>
			<nachname>Zottel</nachname>
			<postleitzahl>13023</postleitzahl>
			<stadt>Zotenheim</stadt>
			<strasse>Soddelstrudel</strasse>
			<haus-nummer>5a</haus-nummer>
		</leistungs-empfaenger>
		<ausstellungsdatum>2017-08-08</ausstellungsdatum>
		<rechnungsnummer>98-798-7987</rechnungsnummer>
		<entgelt>
			<rechnungsbetrag>
				<betrag>621.94</betrag>
				<waehrung>EUR</waehrung>
			</rechnungsbetrag>
			<nettobetrag>
				<betrag>490.22</betrag>
				<waehrung>EUR</waehrung>
			</nettobetrag>
			<mehrwertsteuer-gesamt>
				<betrag>116.74</betrag>
				<waehrung>EUR</waehrung>
			</mehrwertsteuer-gesamt>
		</entgelt>
		<abrechnungs-positionen>
			<abrechnungs-position positionsnummer="1">
				<menge>3</menge>
				<einheit>Packungen</einheit>
				<leistung>Grippemittel Tumifla</leistung>
				<einzel-preis>
					<betrag>120.00</betrag>
					<waehrung>EUR</waehrung>
				</einzel-preis>
				<gesamt-preis>
					<betrag>360.00</betrag>
					<waehrung>EUR</waehrung>
				</gesamt-preis>
				<mehrwertsteuer-prozent>19</mehrwertsteuer-prozent>
			</abrechnungs-position>
			<abrechnungs-position positionsnummer="2">
				<menge>2</menge>
				<einheit>Liter</einheit>
				<leistung>Abf√ºhrmittel Wech damit</leistung>
				<einzel-preis>
					<betrag>99.99</betrag>
					<waehrung>EUR</waehrung>
				</einzel-preis>
				<gesamt-preis>
					<betrag>199.98</betrag>
					<waehrung>EUR</waehrung>
				</gesamt-preis>
				<mehrwertsteuer-prozent>19</mehrwertsteuer-prozent>
			</abrechnungs-position>
			<abrechnungs-position positionsnummer="3">
				<menge>2</menge>
				<einheit>Stueck</einheit>
				<leistung>Energieriegel Satto</leistung>
				<einzel-preis>
					<betrag>5.98</betrag>
					<waehrung>EUR</waehrung>
				</einzel-preis>
				<gesamt-preis>
					<betrag>11.96</betrag>
					<waehrung>EUR</waehrung>
				</gesamt-preis>
				<mehrwertsteuer-prozent>7</mehrwertsteuer-prozent>
			</abrechnungs-position>
		</abrechnungs-positionen>
	</rechnung>
</rechnungen>
