=== Lefted/Deklarative-Programmierung-Uebung/src/de/hka/xml/blaetter/example.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="mein.namespace"
	elementFormDefault="qualified"
	xmlns="mein.namespace"
	>
	<xs:element name="rechneruebung">
		<xs:complexType>
			<xs:choice>
				<xs:element name="aufgabe" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="student" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="name" type="xs:normalizedString" />
										<xs:choice>
											<xs:element name="bestanden" />
											<xs:element name="nicht-bestanden" />
										</xs:choice>
									</xs:sequence>
									<xs:attribute name="matrikelnummer" type="xs:normalizedString" use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:choice>
			<xs:attribute name="name" type="xs:normalizedString"
				use="required" />
		</xs:complexType>
	</xs:element>
	<xs:complexType name="event-type">
		<xs:all>
			<xs:element name="name" type="xs:normalizedString" />
			<xs:element name="start" type="xs:date" />
		</xs:all>
	</xs:complexType>
</xs:schema>

=== Lefted/Deklarative-Programmierung-Uebung/src/de/hka/xml/blaetter/Blatt3_2.xml
<?xml version="1.0" encoding="UTF-8"?>
<rechneruebung
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="mein.namespace example.xsd"
	xmlns="mein.namespace"
	name="XML"
>
	<aufgabe>
		<student matrikelnummer="60000">
			<name>Arnold Adams</name>
			<bestanden />
		</student>
		<student matrikelnummer="60001">
			<name>Anna Albers</name>
			<bestanden />
		</student>
	</aufgabe>
	<aufgabe>
		<student matrikelnummer="60000">
			<name>Arnold Adams</name>
			<nicht-bestanden />
		</student>
	</aufgabe>
</rechneruebung>
